# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-17 21:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('url', models.CharField(max_length=200)),
                ('thumbnailUrl', models.CharField(max_length=200)),
                ('level', models.CharField(max_length=200)),
            ],
        ),
    ]
