# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-27 15:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coursee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=2000)),
                ('description', models.TextField()),
                ('url', models.CharField(max_length=200, unique=True)),
                ('thumbnailUrl', models.CharField(max_length=200)),
                ('level', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='Course',
        ),
    ]
