# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-27 23:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20161027_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='thumbnailUrl',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='course',
            name='url',
            field=models.CharField(max_length=500, unique=True),
        ),
    ]
