# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-29 17:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_auto_20161029_1349'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='course',
            unique_together=set([]),
        ),
    ]
